---
- name: "PLAY 1 - demo utilisation playbook"
  # Target/Pattern  à qui s'adresse le PLAY
  hosts: all
  become: true

  
  vars:
    deploy_pwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30393161373166383932343635663064313162363766363733373461343937376534346561363630
          3833383566323333316635646131666562393562303865330a303338666635323364373730663938
          62663637623735383230313563373231643763346637383738636464613061633637376434326466
          6136653233636332330a326334626233653238396461633164393337636634613261666662343432
          6137
    #deploy_pwd: $6$password$QSrnnf58znEKU41eJcN9cgKLOp4gkp5XXR6.j1hiiS9mHH2JhLIkZVNYjSkbYypqVVZR1nlgzeDCTuFzMmpMo0
    
    #vars_prompt:
  #  - name: password
  #    prompt: What is deploy password?
  #    encrypt: sha512_crypt


  # Déclaration du block tasks : appel des modules ansible
  tasks:
    - name: "Ajout de l'utilisateur de deploiement via ansible"
      ansible.builtin.user:
        name: deploy
        state: present
        shell: /bin/bash
        password: "{{ deploy_pwd | string | password_hash('sha512') }}"
        #update_password: on_create
        #password: "{{ deploy_pwd }}"
        # 3 - password: "{{ password }}"
    
    - name: "Dépose de la clé publique du ansible mgmt chez le user deploy"
      ansible.posix.authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: "Deploiement du fichier de regle sudo pour le user deploy"
      ansible.builtin.copy:
        dest: /etc/sudoers.d/deploy
        content: "deploy ALL=(ALL) NOPASSWD:ALL"
        mode: 0440
        owner: root
        group: root